
name: Hosting deploy

on:
  workflow_run:
    workflows: ["Pre-Deploy checks"]  # Replace with the name of your first workflow
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Second Workflow
        run: 
          
