name: Update Python Line by Line Number

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update_line:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Update Python File
        run: |
          LINE_NUMBER=34  # Replace with the desired line number
          NEW_LINE="run_nightly = False"  # Replace with the new content
          sed -i "${LINE_NUMBER}s/.*/${NEW_LINE}/" core.py
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add core.py
          git commit -m "Update line ${LINE_NUMBER}"
          git push origin main  # Adjust the branch name if needed
