name: Staging for Deploy

on:
  workflow_dispatch

jobs:
  update_line:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: run_nightly = False
        run: |
          LINE_NUMBER=3  # Replace with the desired line number
          NEW_LINE="run_nightly = False"  # Replace with the new content
          sed -i "${LINE_NUMBER}s/.*/${NEW_LINE}/" .env
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .env
          git commit -m "Staging for deploy"
          git push origin main  # Adjust the branch name if needed
        continue-on-error: true
